trigger:
  branches:
    include:
      - refs/tags/release-bindings-v*

pr: none

pool:
  vmImage: "macOS-15"

variables:
  - group: nuget.org

steps:
  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      useGlobalJson: true

  - bash: |
      echo "##vso[build.updatebuildnumber]pullrequests-tonestro-maui-facebookslim-android-$(Build.SourceBranchName)-$(Build.BuildId)"
    displayName: Set Build Number

  - bash: |
      sudo dotnet workload restore
    displayName: Restore Workloads

  - bash: |
      cd java/facebookslim
      ./gradlew build
      cd ../..
    displayName: Gradle Build

  - bash: |
      cd Tonestro.Maui.FacebookSlim.Droid
      dotnet build -c Release
      dotnet pack -c Release
      cd ..
    displayName: Build and Pack

  - bash: |
      cd Tonestro.Maui.FacebookSlim.Droid/nugetoutput
      numberOfNugetFiles=$(ls *.nupkg | wc -l)
      if [[ numberOfNugetFiles -ne 1 ]]; then
        echo "WRONG NUMBER OF NUGET FILES: ${numberOfNugetFiles}"
        exit 1
      fi
      eval $(stat -s *.nupkg)
      if [[ $st_size -lt 1500000 ]]; then
        echo "NUGET FILE TOO SMALL: ${st_size}"
        exit 1
      else
        echo "NUGET SIZE: ${st_size}"
      fi
      numberOfSymbolFiles=$(ls *.snupkg | wc -l)
      if [[ numberOfSymbolFiles -ne 1 ]]; then
        echo "WRONG NUMBER OF SYMBOL PACKAGE FILES: ${numberOfSymbolFiles}"
        exit 1
      fi
      eval $(stat -s *.snupkg)
      if [[ $st_size -lt 10000 ]]; then
        echo "SYMBOL PACKAGE FILE TOO SMALL: ${st_size}"
        exit 1
      else
        echo "SYMBOL PACKAGE SIZE: ${st_size}"
      fi
      cd ../..
    displayName: Check nuget file

  - task: PublishBuildArtifacts@1
    displayName: publish nugetoutput
    inputs:
      PathtoPublish: "Tonestro.Maui.FacebookSlim.Droid/nugetoutput"
      ArtifactName: "nugetoutput"
      publishLocation: "Container"
      StoreAsTar: true

  # Pushing the .nupkg also pushes the .snupkg lying next to it to the
  # nuget.org symbol server (see
  # https://learn.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg)
  - bash: |
      dotnet nuget push Tonestro.Maui.FacebookSlim.Droid/nugetoutput/Tonestro.Maui.FacebookSlim.Droid.*.nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json

  - task: GitHubRelease@1
    inputs:
      gitHubConnection: "tonestro facebook slim ado"
      repositoryName: "tonestro/Tonestro.Maui.FacebookSlim.Droid"
      action: "create"
      target: "$(Build.SourceVersion)"
      tagSource: "userSpecifiedTag"
      tag: "$(Build.SourceBranchName)"
      title: "Tonestro.Maui.FacebookSlim.Droid $(bindingsVersion)"
      assets: |
        Tonestro.Maui.FacebookSlim.Droid/nugetoutput/Tonestro.Maui.FacebookSlim.Droid.*.nupkg
        Tonestro.Maui.FacebookSlim.Droid/nugetoutput/Tonestro.Maui.FacebookSlim.Droid.*.snupkg
      changeLogCompareToRelease: "lastFullRelease"
      changeLogType: "issueBased"
